### ISSUE TITLE
ANGEL classifier training: not UTR file

### ISSUE THREAD

**Issue by uso2015** [PacificBiosciences/ANGEL#10]
Hi @nlhepler @Magdoll 
     “angel_train.py takes a CDS FASTA file and a UTR FASTA file and outputs a trained classifier pickle file.”
      if I haven't the UTR file, such as the species 'saccharomyces_cerevisiae', can I use the ANGEL to do Open Reading Frame prediction ?

**Comment by Magdoll** [comment]
@uso2015 , the UTR file is used to model "background" (genomic regions that are not protein coding). If you already have a CDS file for yeast, you can make a UTR file using regions immediately upstream and downstream of the known CDS regions in yeast (I would take probably 200-500 bp). If there are closely adjacent genes, you will want to select the region carefully and make sure you don't accidentally include CDS in your UTRs.

**Comment by Magdoll** [comment]
Close unless OP re-opens.
