### ISSUE TITLE
Some problem about CD-HIT when using angel_make_training_set.py

### ISSUE THREAD

**Issue by lijl459** [PacificBiosciences/ANGEL#15]
Hellow,
  After I finished the Dumb ORF prediction step, three files were generated, like ANGEL.utr, ANGEL.pep and ANGEL.cds. The ANGEL.cds file is the  nucleotide sequence. However, when I the used the angel_make_training_set.py, it ran the CD-HIT program and the flowing is the command:
  "Program: CD-HIT, V4.7 (+OpenMP), Jun 27 2017, 17:58:25
  Command: cd-hit -T 8 -M 0 -i ANGEL.cds -o ANGEL.nr90.cds -c 0.90 -n 5"
  I want to ask your kind mind whether I can use the 'cd-hit-est' command take the place of "cd-hit". And when the input file is ANGEL.cds, it would take a lot of time to run.
  Thanks very much!

**Comment by Magdoll** [comment]
Hi @lijl459 ,
There should be no problem using cd-hit-est but parameters may be slightly different? Let me know if you run into issues.
