### ISSUE TITLE
A problem with running ANGEL

### ISSUE THREAD

**Issue by ClearloveMiao** [PacificBiosciences/ANGEL#16]
I'm learning ANGEL this days, and when I was running 'angel_train.py', I have encountered such errors:

### **Traceback (most recent call last):
  File "/wtmp/user181/software/Anaconda/ANGEL/angel_train.py", line 22, in <module>
    ANGEL_training(args.cds_filename, args.utr_filename, args.output_pickle, num_workers=args.cpus)
  File "/wtmp/user181/software/Anaconda/ANGEL/build/lib.linux-x86_64-2.7/Angel/SmartORF.py", line 96, in ANGEL_training
    data_pos = get_data_parallel(o_all, coding, [0], num_workers)
  File "/wtmp/user181/software/Anaconda/ANGEL/build/lib.linux-x86_64-2.7/Angel/SmartORF.py", line 61, in get_data_parallel
    obj = queue.get(timeout=60)
  File "/wtmp/user181/software/Anaconda/anaconda2/lib/python2.7/multiprocessing/queues.py", line 132, in get
    raise Empty
Queue.Empty**

And the script just like the below:

### **python /wtmp/user181/software/Anaconda/ANGEL/angel_train.py /wtmp/user181/data/cu_hq_pac/isoform.fl_nr.dumb.final.training.cds /wtmp/user181/data/cu_hq_pac/isoform.fl_nr.dumb.final.training.utr /wtmp/user181/data/cu_hq_pac/isoform.fl_nr.dumb.final.classifier.pickle --cpu 2**

I don't know how to deal with this problem, so can you give me some suggestions to help me?
Thanks a lot!

**Comment by Magdoll** [comment]
Hi @ClearloveMiao ,
It looks like the input files may be empty?

Can you check the files
```
ls -lh /wtmp/user181/data/cu_hq_pac/isoform.fl_nr.dumb.final.training.cds 
ls -lh /wtmp/user181/data/cu_hq_pac/isoform.fl_nr.dumb.final.training.utr 
```

**Comment by ClearloveMiao** [comment]
Hi @Magdoll
I have checked the input files, the two files are not empty. Just like the below:

`-rw-rw-r-- 1 user181 user181 2.0M 2018-04-09 20:58 /wtmp/user181/data/cu_hq_pac/isoform.fl_nr.dumb.final.training.cds`

`-rw-rw-r-- 1 user181 user181 364K 2018-04-09 20:58 /wtmp/user181/data/cu_hq_pac/isoform.fl_nr.dumb.final.training.utr`

So, I don't know how to do next. and I have run the script again, and it has reported such errors:

`all workers done!`
`retrieved 666454 data items`
`launching all workers`
`launching worker Process-9`
`Traceback (most recent call last):`
`   File "/wtmp/user181/software/Anaconda/ANGEL/angel_train.py", line 22, in <module>`
`    ANGEL_training(args.cds_filename, args.utr_filename, args.output_pickle, num_workers=args.cpus)`
`  File "/wtmp/user181/software/Anaconda/ANGEL/build/lib.linux-x86_64-2.7/Angel/SmartORF.py", line 97, in ANGEL_training`
`    data_neg = get_data_parallel(o_all, utr, [0, 1, 2], num_workers)`
`  File "/wtmp/user181/software/Anaconda/ANGEL/build/lib.linux-x86_64-2.7/Angel/SmartORF.py", line 54, in get_data_parallel`
`    p.start()`
`   File "/wtmp/user181/software/Anaconda/anaconda2/lib/python2.7/multiprocessing/process.py", line 130, in start`
`    self._popen = Popen(self)`
`  File "/wtmp/user181/software/Anaconda/anaconda2/lib/python2.7/multiprocessing/forking.py", line 121, in __init__`
`    self.pid = os.fork()`
`OSError: [Errno 12] Cannot allocate memory`

I'm very puzzled about this problem.

**Comment by Magdoll** [comment]
It looks like it is out of memory. The input files don't look particularly big. Can you check the memory usage of the machine while it's running?

**Comment by ClearloveMiao** [comment]
@Magdoll It seems like this `angel_train.py` has take on so many memory and the worst thing is our server has broken down because of that.........

So, what can do to reduce the memory usage? Can I cut the 500 refseq of `pacbio.fl_nr.dumb.final.training.cds` to 250 refseq? And how to do with the `pacbio.fl_nr.dumb.final.training.utr`?

**Comment by ClearloveMiao** [comment]
@Magdoll 
I also have an another questions about `angle_training.py`. When I run this python script at the first time, I have encountered some errors, so I have added some scripts in the `angle_training.py`, just like this:

`import os`
`import sys`
`sys.path.append('/wtmp/user181/software/Anaconda/ANGEL/build/lib.linux-x86_64-2.7')`
`sys.path.append('/wtmp/user181/software/Anaconda/anaconda2/envs/anaCogent/lib/python2.7/site-packages')`

After I adding these scripts, `angle_training.py` has running successfully. But I'm not sure whether my solution is right. So I show that to you for verification.

**Comment by Magdoll** [comment]
Hi @ClearloveMiao ,

I think you are not activating the Anaconda environment properly. Did you do 

```
source activate Anaconda
```

as described in the tutorial?

You should be able to type
```
which angel_training.py
```
in any directory (try from your home directory) and it should work.

--Liz

**Comment by ClearloveMiao** [comment]
Hi @Magdoll ,
I have activated the Anaconda environment, and my prompt also has changed to 

`(anaCogent) user181@cu02#`

But after I typing 

`which angel_training.py`

in my home directory, it shows 

`/usr/bin/which: no angel_training.py in (/wtmp/user181/software/Anaconda/anaconda2/envs/anaCogent/bin:/wtmp/user181/software/Anaconda/anaconda2/bin:)`

So I don't know why and how to do next, can you give me some advice. Thanks for any suggestions!

**Comment by Magdoll** [comment]
@ClearloveMiao ,

After you are in the Anaconda environment, did you follow the install steps and install ANGEL? 

--liz

**Comment by ClearloveMiao** [comment]
@Magdoll 
Yes, I did. I have followed the install step strictly.

**Comment by Magdoll** [comment]
Hi @ClearloveMiao ,

Can you look at the anaconda bin directory and see if any scripts were installed?

For example, in mine:
```
$ ls -lh /home/anaconda2/envs/anaCogent/bin/angel*py
-rwxr-xr-x 1 etseng Domain Users 228 Jul 10  2017 /home/anaconda2/envs/anaCogent/bin/angel_compare_files.py
-rwxr-xr-x 1 etseng Domain Users 236 Jul 10  2017 /home/anaconda2/envs/anaCogent/bin/angel_make_training_set.py
-rwxr-xr-x 1 etseng Domain Users 216 Jul 10  2017 /home/anaconda2/envs/anaCogent/bin/angel_predict.py
-rwxr-xr-x 1 etseng Domain Users 212 Jul 10  2017 /home/anaconda2/envs/anaCogent/bin/angel_train.py
```

**Comment by MaPengyu** [comment]
@Magdoll,
I have activated the Anaconda environment, and typing,_which angel_training.py_ in my home directory, it shows the same with ClearloveMiao : `/usr/bin/which: no angel_training.py in (xxxxxx)`

while  look at the anaconda bin directory,  it shows:
 `-rwxrwxr-x 1 SMRT_Link SMRT_Link 228 Nov  1 18:02 /share/home/SMRT_Link/anaconda3/envs/anaCogent/bin/angel_compare_files.py
-rwxrwxr-x 1 SMRT_Link SMRT_Link 236 Nov  1 18:02 /share/home/SMRT_Link/anaconda3/envs/anaCogent/bin/angel_make_training_set.py
-rwxrwxr-x 1 SMRT_Link SMRT_Link 216 Nov  1 18:02 /share/home/SMRT_Link/anaconda3/envs/anaCogent/bin/angel_predict.py
-rwxrwxr-x 1 SMRT_Link SMRT_Link 212 Nov  1 18:02 /share/home/SMRT_Link/anaconda3/envs/anaCogent/bin/angel_train.py
`

**Comment by Magdoll** [comment]
Closed unless OP re-opens.
