### ISSUE TITLE
A problem with running angel_train.py

### ISSUE THREAD

**Issue by lijl459** [PacificBiosciences/ANGEL#17]
Dear Magdoll,
        Hellow!
        When I was running angel_train.py to do ANGEL classifier training, I got some trouble here. The command needs more than 400G memory to run, otherwise the memory of our computer  is limit to 124G. So,  what can I do to reduce the memory in this step?
        There are 18000 sequences and 28262787 bases in total  in the dumb.final.cds file.
        Thanks a lot!

**Comment by Magdoll** [comment]
Hi @lijl459 ,
You could downsample the ANGEL training set. See [tutorial here](https://github.com/PacificBiosciences/ANGEL#trainset). You could use `--use_top=5000` to limit training to, say, the top 5000 sequences.

--LIz

**Comment by lijl459** [comment]
@Magdoll Very thanks for your reply. I will try it latter.
