### ISSUE TITLE
Cant extract all .cds predictions with a simple grep - only type:confident

### ISSUE THREAD

**Issue by EmilyAmor** [PacificBiosciences/ANGEL#19]
Hi,

Here's my code for running `angel_predict.py` in **output_mode=best**  **and output_mode=all** respectively:
a) `angel_predict.py transcripts.fasta dumb.final.classifier.pickle best_predictions --use_rev_strand --output_mode=best `
b) `angel_predict.py transcripts.fasta dumb.final.classifier.pickle all_predictions --use_rev_strand --output_mode=all`

my output **best_predictions.cds** and **all_predictions.cds** has a few **type:suspicious** predictions for the same contig and I can't extract their fasta headers with the standard `grep "^>"` command; I only get the headers that have the **type:confident** in them as output.  

Therefore, my questions are:
1) Why does **--output_mode=best** give more than one prediction per contig
2) Are **types** that are = Confident encoded differently, therefore making them hidden for grep detection?

Kind regards,
Emily

**Comment by Magdoll** [comment]
Hi @EmilyAmor ,

I'm not sure what problem is with your grep. I have no trouble grepping for **type:suspicious**. Here's an example on one of my ANGEL runs:
```
$ grep "^>" touse.ANGEL_or_genome.best.cds|grep "type:suspicious"|head -n 5
>PB.27.1|chr1:26169840-26170869(+)|HQ_sampleX|cb1_c2655/f3p0/644|m.33 type:suspicious-NA len:154 strand:+ pos:1-462
>PB.34.2|chr1:32886330-32894647(+)|HQ_sampleX|cb1_c992/f2p0/1409|m.41 type:suspicious-NA len:210 strand:+ pos:1-630
>PB.52.1|chr1:46394271-46413846(+)|HQ_sampleX|cb1_c192/f31p0/2090|m.71 type:suspicious-NA len:606 strand:+ pos:1-1818
>PB.65.1|chr1:111691376-111713113(+)|HQ_sampleX|cb1_c1080/f2p0/1255|m.83 type:suspicious-NA len:134 strand:+ pos:141-542
>PB.66.2|chr1:112619832-112671041(+)|HQ_sampleX|cb1_c376/f10p0/1786|m.85 type:suspicious-NA len:291 strand:+ pos:3-875
```

re: **--output_mode=best**. The behavior for **--output_mode=best** for ANGEL is that if there are multiple ORFs (suspicious), it would output all of them. It gets more complicated if you also allow reverse strand predictions and consider dumb predictions. The full decision is documented [here](https://github.com/PacificBiosciences/ANGEL/blob/master/src/SmartORF.py#L127). 


```
Output Mode is either "best" or "all"
    If "all" and + strand only: ANGEL+, dumb+  (both subject to its length threshold)
    If "all" and - strand also: ANGEL+, dumb+, ANGEL-, dumb-
    If "best" and + strand only: argmax_(ANGEL+, dumb+)
    If "best" and - strand also: argmax_(ANGEL+, dumb+, ANGEL-, dumb-)
    For dumb, pick only the longest ORF ouf of the 3 possible frames for that strand.
    For ANGEL, if there are multiple ORFs (suspicious), 
         the longest one is chosen as the "length" to beat dumb, 
         and if ANGEL is chosen as output, all ORFs are output.
```
