### ISSUE TITLE
Can not get the 'pickle' file when running 'angle train.py'

### ISSUE THREAD

**Issue by ClearloveMiao** [PacificBiosciences/ANGEL#21]
when I run `angle_train.py` , I can not get the pickle file, and the program is running like below picture.

![image](https://user-images.githubusercontent.com/37678675/47913272-74475680-ded6-11e8-938e-4db3f6adc289.png)

And the script is like below:
`angel_train.py cu.predict.final.training.cds cu.predict.final.training.utr cu.predict.final.classifier.pickle --cpus 4`

So, I want to know the reason why I cannot get the pickle file.

Thanks a lot.

**Comment by Magdoll** [comment]
Hi,
That means the training is still running.

--Liz

**Comment by ClearloveMiao** [comment]
But it showed the program has stopped......Maybe this program has taken too much resource and host shut down it .........
