### ISSUE TITLE
ANGEL intermidiate files clean up

### ISSUE THREAD

**Issue by aksenia** [PacificBiosciences/ANGEL#22]
Hi Liz, 

This is not really an issue, but I would like to double check one thing about angel run. I run successfully all steps and in the last step the script finished with:
"Closing Pool....
Joining Pool....
All workers completed.
Output written to data.ANGEL.cds, data.ANGEL.pep, data.ANGEL.utr
"
But in the angel folder I see a bunch of intermidiate files that were not deleted - 176 data.split_*.fa and data.split_*fa.ANGEL, data.split_*fa.ANGEL.DONE. 
There are also files data.ANGEL.cds, data.ANGEL.pep, data.ANGEL.utr which I take is a final output. I wonder whether it is normal that the intermidiate files are not deleted? Since the tool run for a while I do not feel like deleting them in case if it means the run is incomplete. 

Best
Ksenia

**Comment by Magdoll** [comment]
HI @aksenia ,

The intermediate file clean up was previously commented out. See the last lines in [SmartORF.py](https://github.com/PacificBiosciences/ANGEL/blob/master/src/SmartORF.py#L311).

I can check in a version later that has those lines uncommented. You can also uncomment them and recompile.

--Liz

**Comment by Magdoll** [comment]
Intermediate files are now cleaned up in v2.7. Closing issue.
