### ISSUE TITLE
Some questions about cds analysis

### ISSUE THREAD

**Issue by WayneForever** [PacificBiosciences/ANGEL#25]
Hi,

These days I'm working on a small transcriptome project where I use the ANGEL software to predict the potential cds sequences. 

I first inputted the Pacbio-based reads and used TOFU software to get transcript sequences with the number of 5027. Then I did LncRNA analysis and got LncRNA sequences with the number of 948. I then followed the steps on the ANGEL manual and I have already got some cds results. 

However, there are some questions that seem a little bit confusing to me:

Question 1: The total number of cds sequences is 5354. I found that there are some transcripts that have more than 1 cds sequence. So I chose the longest cds in this type of transcript. The final number of cds is 4712. 
However, if you do a simple calculation, you will find that the sum of cds and LncRNA is 4712 + 948 = 5660, which much larger than 5027. I'm wondering why the result goes like this with correct inputs.

Question 2: In your ANGEL manual, you listed the potential result types like this:
`<seq_id> type:<tag>-<completeness> len:<ORF length (aa)> strand:<strand> pos:<CDS range>`
'Where tag is confident, likely, or suspicious for ANGEL predictions, and dumb for dumb ORF predictions.
completeness is either complete, 5partial, 3partial, or internal based on the presence or absence of start and stop codons.'
However, I found that there is another type of completeness named NA. What does it mean?

Question 3: As I mentioned in Question 1, there are some transcripts that have more than 1 predicted cds sequence. What is the criteria of my choice? The first one? The longest one? Or should I keep all of them?

Question 4: Based on your research experience, could you please give me some suggestion about the proper order of the analysis that I have done, which means the order of LncRNA analysis, CDS prediction and novel transcript annotation?

Thank you very much for this good software and I'm very appreciate your answer.

Best

**Comment by Magdoll** [comment]
Hi @WayneForever , if you still need me to answer these questions let me know. Otherwise closing issue.
