### ISSUE TITLE
CD HIT

### ISSUE THREAD

**Issue by rsalz** [PacificBiosciences/ANGEL#28]
with ANGEL i can specify the number of cpus with the "--cpus" option, but when CD-HIT runs (the first step of dumb_prediction), it only uses 1 thread no matter how many cpus I specified on the command line. This slows down execution considerably.

**Comment by Magdoll** [comment]
Hi @rsalz ,

I think you're right, however since CD-HIT is not my software, I'm not sure there's anything I can do :(

--Liz
