### ISSUE TITLE
Q: ORFs of NA type

### ISSUE THREAD

**Issue by emaleckova** [PacificBiosciences/ANGEL#33]
Hello Liz,

I have got a question. After running ANGEL, I realized that to roughly a third of the obtained ORFs "NA" prediction type was assigned. Of those cases, about half is classified as 'likely' and the other half as 'suspicious'. I am wondering whether something like this is normally observed or whether I should be concerned about those "NA" instances.

Could it be that those ORFs come from heavily degraded RNA since the algorithm was not able to even assign a "degradation type"?

Thank you very much.

Best,
Eva

**Comment by Magdoll** [comment]
Hi @emaleckova , let me know if you still want me to look into this - otherwise closing issue :-)
