### ISSUE TITLE
angel_predict.py takes forever with --use_rev_strand option

### ISSUE THREAD

**Issue by LiorFaigon** [PacificBiosciences/ANGEL#35]
Hi,
I'm working on a transcriptome that uses both PacBio and Ilumina reads but the --use_rev_strand option makes the process last for weeks. after a couple of weeks it is still running without much progress.
I'm using ANGEL version 2.7 and the command is:
angel_predict.py file.fasta filename.dumb.final.classifier.pickle filename_ANGEL --use_rev_strand --output_mode=best  --min_angel_aa_length 30 --min_dumb_aa_length 30
Thanks in advance,
Lior

**Comment by Magdoll** [comment]
Hi @LiorFaigon ,
Can you let me know the number of input sequences in file.fasta?
You can check by doing `grep -c ">" file.fasta` on the command line?
And, would you be willing to share the data confidentially for me to test?

Thanks,
-Liz

**Comment by LiorFaigon** [comment]
Hi Liz,
Thank you for your reply, the number of input sequences is 81.5K, but i tried it with just 500 sequences as input and it also never finished.
Checking on the option to share the data.
-Lior

**Comment by Magdoll** [comment]
> Hi Liz,
> Thank you for your reply, the number of input sequences is 81.5K, but i tried it with just 500 sequences as input and it also never finished.
> Checking on the option to share the data.
> -Lior

I can send a request for data secure upload if you can give me an email to send the request to.

**Comment by LiorFaigon** [comment]
Thank you, my email is lior.faigon@weizmann.ac.il

**Comment by Magdoll** [comment]
Hi @LiorFaigon , a file request has been sent to the email.

**Comment by Magdoll** [comment]
Hi @LiorFaigon ,
ANGEL is now updated to v3.0, which uses Python 3.7 (this does mean you have to create a new anaconda environment with Python 3.7, apologies for additional hassle, but all my other tools have moved to Python 3). I also fixed the issue that `--use_rev_strand` was causing. You should receive the updated ANGEL results through portal. Let me know how it goes.
Thanks!
-Liz

**Comment by LiorFaigon** [comment]
Hi Liz, 
The update did it!
Thank you
-Lior
