### ISSUE TITLE
Bio.Alphabet has been removed from Biopython 1.78

### ISSUE THREAD

**Issue by yy-liang** [PacificBiosciences/ANGEL#37]
Hi @Magdoll,
I'm using Bioython 1.78 to run the ANGEL v3.0 and I got this error:

`Traceback (most recent call last):
  File "angel_train.py", line 4, in <module>
    from Angel.SmartORF import ANGEL_training
  File "/root/anaconda3/envs/py37/lib/python3.7/site-packages/Angel-3.0-py3.7-linux-x86_64.egg/Angel/SmartORF.py", line 13, in <module>
    from Angel import c_ORFscores, ORFscores, DumbORF
  File "c_ORFscores.pyx", line 5, in init c_ORFscores
  File "/root/anaconda3/envs/py37/lib/python3.7/site-packages/Bio/Alphabet/__init__.py", line 21, in <module>
    "Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information."
ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information.` 

Any advice will be appreciated.

Best wishes!

**Comment by Johnsonzcode** [comment]
Hello, same situation.
Solved by adding '#' in python3.7/site-packages/Angel-3.0-py3.7-linux-x86_64.egg/Angel/ORFscores.py at the line 6 beginning.

**Comment by NiuNiuguohao** [comment]
> 
> 
> Hello, same situation.
> Solved by adding '#' in python3.7/site-packages/Angel-3.0-py3.7-linux-x86_64.egg/Angel/ORFscores.py at the line 6 beginning.

Hello！I met the same problem and  tried your solution. But it didn't work. 
If there's any other solution?  Thanks a lot!

**Comment by Magdoll** [comment]
HI @NiuNiuguohao ,

Unfortunately ANGEL is getting deprecated and I will no longer be supporting fixes.
Apologies. We now recommend using [GeneMark](http://opal.biology.gatech.edu/GeneMark/) for ORF predictions.
If you have a reference genome & annotation, you may also want to check out [SQANTI3](https://github.com/ConesaLab/SQANTI3) which calls GeneMark as part of the process.

-Liz
