### ISSUE TITLE
angel_train.py hanging with refseq sequences

### ISSUE THREAD

**Issue by sjin09** [PacificBiosciences/ANGEL#6]
Dear Magdoll,

I am writing to inquire whether it was possible for you to train the known refseq sequences with ANGEL. I have downloaded the refseq sequences from ftp://ftp.ncbi.nlm.nih.gov/refseq/H_sapiens/mRNA_Prot/. Thereafter I selected the sequences that are known by selecting sequences that starts with "NM_" and removed sequences with unambiguous sequences such as "N".

I have been successful with dumb_predict.py, angel_make_training_set.py, but angel_train.py hangs after printing "Done with records". 

Do you have any tips on using the refseq sequences in predicting the open reading frame from the isoseqs? Do you otherwise recommend using the isoseqs itself for training and predicting the ORF in the isoseqs? I thought we should keep the training set and the prediction set separate.

Best,
Jin

**Comment by Magdoll** [comment]
Hi Jin,
How big is the training set? I have found that ANGEL training sometimes hang if either happens:

--- the dataset is too big and it's consuming all the memory (you can check this with `free -g`)
--- the multiprocessing module in Python sometimes hang (have trouble passing these large datasets) if you use too many CPUs. I have found that using up to 12 CPUs is fine but more than that, sometimes the Queue module just gets stuck and does nothing. I have tried debugging it but have not found a better solution other than lowering the CPU count to minimize the chance of hanging.

Re: training --- if you are predicting ORFs on human or another species that has plenty of RefSeq sequences, it is perfectly fine to use RefSeq. Many ANGEL users are predicting it on non-model organisms and the coding features may look very different, hence using a subset of the dataset to train for classifier is actually better. 

I just added two very recently trained pickles to ANGEL:
https://github.com/PacificBiosciences/ANGEL/tree/master/trained_pickles

one is based on the MCF-7 dataset. one is based on the recently released Alzheimer brain dataset.

I can certainly train a RefSeq dataset if that's what you need.

**Comment by sjin09** [comment]
Using angel_make_training_set.py, I randomly selected 500 refseq sequences for angel_train.py. The original refseq set has 50,873 sequences. I have used 12 CPUS to run angel_train.py and the total memory of the server 1000G, so I don't think the memory is the major problem.

I am indeed using the human refseq sequences for creating the training set. I am slightly worried about using the isoseq sequences itself for training as there would be long-noncoding RNAs that can possibly train the software spuriously. It would be great if you could provide the refseq dataset! 

Should I send you the human refseq sequences that I have been trying to perform the training on?

**Comment by Magdoll** [comment]
Yes you can email the dataset for training to etseng@pacb.com.

I doubt NCrnas will influence the training. By their nature there is no predicted ORF. Angel only trains on sequences where there is a predicted ORF. If anything the NCrnas will be used as "negative control" (sequences in which there is no coding potential)

**Comment by sjin09** [comment]
I have moved retrained the refseq sequence with more memory from the very start, and I have been able to successfully create the training set! Thank you so much for the help.

**Comment by sjin09** [comment]
Do you think the criteria that you have created for predicting the ORF is also sufficient to determine whether the sequence is coding or noncoding, and thereby determining that the sequence is a noncoding RNA? I was thinking of using PLEK or CPAT to determine whether the isoseq is a noncoding RNA, but if ANGEL has this function

**Comment by Magdoll** [comment]
@sjin09  for ncRNA prediction CPAT/PLEK is the way to go. There is a pipeline made for PacBio data at: https://bitbucket.org/arrigonialberto/lncrnas-pipeline

**Comment by ClearloveMiao** [comment]
@sjin09 What method has you taken to deal with your problem `Done with records`. Can you describe it more detail? Thanks a lot!

**Comment by filidi** [comment]
@Magdoll Just a note for the next person to run into this, the newest scikit-learn release that the Sep 26, 2016 pre-trained pickles work with is 0.17.1. Later versions have broken compatibility for saved estimators.
